export const conversationVolumeData = [
  { date: '24 Apr', total: 142, aiDeflected: 61, human: 81 },
  { date: '25 Apr', total: 168, aiDeflected: 74, human: 94 },
  { date: '26 Apr', total: 95, aiDeflected: 39, human: 56 },
  { date: '27 Apr', total: 78, aiDeflected: 31, human: 47 },
  { date: '28 Apr', total: 201, aiDeflected: 91, human: 110 },
  { date: '29 Apr', total: 187, aiDeflected: 82, human: 105 },
  { date: '30 Apr', total: 156, aiDeflected: 70, human: 86 },
  { date: '1 May', total: 223, aiDeflected: 103, human: 120 },
  { date: '2 May', total: 198, aiDeflected: 89, human: 109 },
  { date: '3 May', total: 174, aiDeflected: 76, human: 98 },
  { date: '4 May', total: 89, aiDeflected: 36, human: 53 },
  { date: '5 May', total: 71, aiDeflected: 29, human: 42 },
  { date: '6 May', total: 241, aiDeflected: 114, human: 127 },
  { date: '7 May', total: 263, aiDeflected: 127, human: 136 },
  { date: '8 May', total: 218, aiDeflected: 99, human: 119 },
  { date: '9 May', total: 189, aiDeflected: 86, human: 103 },
  { date: '10 May', total: 134, aiDeflected: 61, human: 73 },
];

export const frtTrendData = [
  { date: '24 Apr', frt: 8.4, sla: 5 },
  { date: '25 Apr', frt: 7.2, sla: 5 },
  { date: '26 Apr', frt: 6.1, sla: 5 },
  { date: '27 Apr', frt: 5.8, sla: 5 },
  { date: '28 Apr', frt: 9.3, sla: 5 },
  { date: '29 Apr', frt: 7.6, sla: 5 },
  { date: '30 Apr', frt: 6.4, sla: 5 },
  { date: '1 May', frt: 11.2, sla: 5 },
  { date: '2 May', frt: 8.7, sla: 5 },
  { date: '3 May', frt: 5.3, sla: 5 },
  { date: '4 May', frt: 4.9, sla: 5 },
  { date: '5 May', frt: 4.2, sla: 5 },
  { date: '6 May', frt: 6.8, sla: 5 },
  { date: '7 May', frt: 7.1, sla: 5 },
  { date: '8 May', frt: 5.9, sla: 5 },
  { date: '9 May', frt: 4.7, sla: 5 },
  { date: '10 May', frt: 3.8, sla: 5 },
];

export const deflectionByTopicData = [
  { topic: 'Order Tracking', deflected: 312, escalated: 28 },
  { topic: 'Delivery Status', deflected: 267, escalated: 41 },
  { topic: 'Return Policy', deflected: 198, escalated: 67 },
  { topic: 'Product Info', deflected: 176, escalated: 24 },
  { topic: 'Payment Issues', deflected: 89, escalated: 112 },
  { topic: 'Cancellation', deflected: 143, escalated: 38 },
  { topic: 'Exchange Request', deflected: 94, escalated: 56 },
  { topic: 'Promo/Discount', deflected: 221, escalated: 19 },
];

export const languageDistributionData = [
  { language: 'Bahasa ID', count: 892, pct: 38 },
  { language: 'English', count: 541, pct: 23 },
  { language: 'Hindi', count: 374, pct: 16 },
  { language: 'Thai', count: 211, pct: 9 },
  { language: 'Vietnamese', count: 165, pct: 7 },
  { language: 'Tamil', count: 118, pct: 5 },
  { language: 'Bengali', count: 47, pct: 2 },
];

export const agentPerformanceData = [
  {
    id: 'agent-perf-001',
    name: 'Priya Nair',
    initials: 'PN',
    color: 'bg-purple-100 text-purple-700',
    assigned: 87,
    resolved: 79,
    avgFrt: '3.2 min',
    frtRaw: 3.2,
    csat: 4.7,
    languages: ['EN', 'TA', 'HI'],
    status: 'online',
    onlineHours: '6h 14m',
  },
  {
    id: 'agent-perf-002',
    name: 'Arif Wibowo',
    initials: 'AW',
    color: 'bg-blue-100 text-blue-700',
    assigned: 94,
    resolved: 88,
    avgFrt: '4.1 min',
    frtRaw: 4.1,
    csat: 4.5,
    languages: ['ID', 'EN'],
    status: 'online',
    onlineHours: '7h 02m',
  },
  {
    id: 'agent-perf-003',
    name: 'Thanh Nguyen',
    initials: 'TN',
    color: 'bg-green-100 text-green-700',
    assigned: 61,
    resolved: 54,
    avgFrt: '5.8 min',
    frtRaw: 5.8,
    csat: 4.2,
    languages: ['VI', 'EN'],
    status: 'away',
    onlineHours: '4h 30m',
  },
  {
    id: 'agent-perf-004',
    name: 'Kavitha Rajan',
    initials: 'KR',
    color: 'bg-orange-100 text-orange-700',
    assigned: 72,
    resolved: 61,
    avgFrt: '7.4 min',
    frtRaw: 7.4,
    csat: 3.9,
    languages: ['TA', 'EN', 'HI'],
    status: 'online',
    onlineHours: '5h 48m',
  },
  {
    id: 'agent-perf-005',
    name: 'Marco Santos',
    initials: 'MS',
    color: 'bg-pink-100 text-pink-700',
    assigned: 48,
    resolved: 45,
    avgFrt: '2.9 min',
    frtRaw: 2.9,
    csat: 4.8,
    languages: ['EN', 'BN'],
    status: 'offline',
    onlineHours: '0h 00m',
  },
];