export type ArticleStatus = 'published' | 'draft' | 'archived';
export type ArticleLanguage = 'en' | 'id' | 'th' | 'vi' | 'ta' | 'hi';

export interface KBArticle {
  id: string;
  title: string;
  category: string;
  status: ArticleStatus;
  languages: ArticleLanguage[];
  aiUsageCount: number;
  deflectionScore: number;
  lastUpdated: string;
  author: string;
  content: string;
  views: number;
}

export const categories = [
  'Order Tracking',
  'Returns & Exchanges',
  'Payment & Billing',
  'Shipping & Delivery',
  'Product Information',
  'Account & Profile',
  'Promotions & Discounts',
  'Technical Support',
];

export const articles: KBArticle[] = [
  {
    id: 'kb-001',
    title: 'How to track your order',
    category: 'Order Tracking',
    status: 'published',
    languages: ['en', 'id', 'th', 'vi'],
    aiUsageCount: 1247,
    deflectionScore: 94,
    lastUpdated: '8 May 2026',
    author: 'Priya Nair',
    views: 3821,
    content: `## How to track your order\n\nYou can track your order in three ways:\n\n**1. Via WhatsApp**\nSimply reply "track [order number]" in this chat and our AI will fetch your real-time tracking status.\n\n**2. Via Shopee/Lazada app**\nGo to Me → My Orders → Find your order → Track Package.\n\n**3. Via courier website**\nUse your tracking number (found in your order confirmation SMS) on the JNE, J&T, or SiCepat website.\n\nTracking updates may take 24–48 hours after dispatch.`,
  },
  {
    id: 'kb-002',
    title: 'Return and exchange policy',
    category: 'Returns & Exchanges',
    status: 'published',
    languages: ['en', 'id', 'hi'],
    aiUsageCount: 892,
    deflectionScore: 87,
    lastUpdated: '5 May 2026',
    author: 'Arif Wibowo',
    views: 2134,
    content: `## Return and Exchange Policy\n\nWe accept returns within **7 days** of delivery for the following reasons:\n\n- Item received is damaged or defective\n- Wrong item sent\n- Item does not match the description\n\n**How to initiate a return:**\n1. Take photos of the item and packaging\n2. Send photos to this WhatsApp chat\n3. Our team will approve and arrange a pickup within 24 hours\n\n**Exchanges:** We process exchanges for size/color within 14 days if stock is available.`,
  },
  {
    id: 'kb-003',
    title: 'Payment methods accepted',
    category: 'Payment & Billing',
    status: 'published',
    languages: ['en', 'id', 'th'],
    aiUsageCount: 634,
    deflectionScore: 91,
    lastUpdated: '2 May 2026',
    author: 'Priya Nair',
    views: 1876,
    content: `## Payment Methods\n\nWe accept the following payment methods:\n\n**Online:**\n- Credit/Debit cards (Visa, Mastercard)\n- GoPay, OVO, Dana (Indonesia)\n- PromptPay (Thailand)\n- UPI, Paytm (India)\n\n**On delivery:**\n- Cash on Delivery (COD) available in selected areas\n\n**Installments:**\n- 0% installment via Kredivo or Akulaku for orders above Rp 500,000`,
  },
  {
    id: 'kb-004',
    title: 'Estimated delivery times by region',
    category: 'Shipping & Delivery',
    status: 'published',
    languages: ['en', 'id'],
    aiUsageCount: 1089,
    deflectionScore: 89,
    lastUpdated: '7 May 2026',
    author: 'Thanh Nguyen',
    views: 2987,
    content: `## Estimated Delivery Times\n\n| Region | Regular | Express |\n|--------|---------|----------|\n| Java (same city) | 1–2 days | Same day |\n| Java (inter-city) | 2–3 days | 1–2 days |\n| Sumatra | 3–5 days | 2–3 days |\n| Kalimantan | 4–7 days | 3–4 days |\n| Sulawesi & East | 5–10 days | 4–6 days |\n\nDelivery times are estimates and may vary during peak seasons (Lebaran, Harbolnas).`,
  },
  {
    id: 'kb-005',
    title: 'How to cancel an order',
    category: 'Order Tracking',
    status: 'published',
    languages: ['en', 'id', 'hi', 'ta'],
    aiUsageCount: 743,
    deflectionScore: 82,
    lastUpdated: '6 May 2026',
    author: 'Kavitha Rajan',
    views: 1654,
    content: `## How to Cancel an Order\n\nOrders can be cancelled **before they are shipped**.\n\n**To cancel:**\n1. Reply "cancel [order number]" in this chat\n2. Our AI will check if cancellation is still possible\n3. If confirmed, your refund will be processed within 3–5 business days\n\n**Cannot cancel if:**\n- Order is already packed or shipped\n- Custom or made-to-order items\n\nFor shipped orders, please use our return process instead.`,
  },
  {
    id: 'kb-006',
    title: 'Promo codes and discount usage',
    category: 'Promotions & Discounts',
    status: 'published',
    languages: ['en', 'id'],
    aiUsageCount: 521,
    deflectionScore: 78,
    lastUpdated: '4 May 2026',
    author: 'Arif Wibowo',
    views: 1234,
    content: `## Using Promo Codes\n\nApply promo codes at checkout in the "Voucher" or "Promo Code" field.\n\n**Common issues:**\n- Codes are case-sensitive\n- Each code has a minimum order value\n- Some codes are single-use only\n- Codes cannot be combined with flash sale prices\n\nIf your code isn't working, send it in this chat and we'll verify it for you.`,
  },
  {
    id: 'kb-007',
    title: 'Size guide for clothing items',
    category: 'Product Information',
    status: 'draft',
    languages: ['en'],
    aiUsageCount: 0,
    deflectionScore: 0,
    lastUpdated: '9 May 2026',
    author: 'Priya Nair',
    views: 0,
    content: `## Size Guide\n\n*Draft — pending review by product team before publishing.*\n\nOur sizing follows Indonesian standard measurements. Please refer to the size chart below and measure yourself before ordering to ensure the best fit.`,
  },
  {
    id: 'kb-008',
    title: 'Account password reset',
    category: 'Account & Profile',
    status: 'published',
    languages: ['en', 'id', 'th', 'vi', 'ta', 'hi'],
    aiUsageCount: 387,
    deflectionScore: 96,
    lastUpdated: '1 May 2026',
    author: 'Thanh Nguyen',
    views: 891,
    content: `## Reset Your Password\n\n**Via app:**\n1. Tap "Forgot Password" on the login screen\n2. Enter your registered email or phone number\n3. Check your SMS/email for a 6-digit OTP\n4. Enter OTP and set a new password\n\n**Via WhatsApp:**\nReply "reset password" and we'll send you a secure reset link directly.`,
  },
  {
    id: 'kb-009',
    title: 'Damaged item claim process',
    category: 'Returns & Exchanges',
    status: 'published',
    languages: ['en', 'id'],
    aiUsageCount: 456,
    deflectionScore: 83,
    lastUpdated: '3 May 2026',
    author: 'Kavitha Rajan',
    views: 1102,
    content: `## Claiming a Damaged Item\n\nIf you receive a damaged item, please act within **48 hours of delivery**.\n\n**Required photos:**\n1. Outer packaging (showing shipping label)\n2. Inner packaging\n3. Damaged item close-up\n\nSend all photos to this WhatsApp chat and our team will process your claim within 24 hours. Replacement or full refund will be issued.`,
  },
  {
    id: 'kb-010',
    title: 'Bulk order and B2B enquiries',
    category: 'Product Information',
    status: 'archived',
    languages: ['en'],
    aiUsageCount: 12,
    deflectionScore: 45,
    lastUpdated: '15 Mar 2026',
    author: 'Arif Wibowo',
    views: 234,
    content: `## Bulk Orders\n\n*This article has been archived. Please refer to our updated B2B catalogue page.*`,
  },
  {
    id: 'kb-011',
    title: 'Shopee and Lazada integration FAQ',
    category: 'Technical Support',
    status: 'draft',
    languages: ['en', 'id'],
    aiUsageCount: 0,
    deflectionScore: 0,
    lastUpdated: '10 May 2026',
    author: 'Raj Sharma',
    views: 0,
    content: `## Platform Integration FAQ\n\n*Draft — in progress. Will cover Shopee and Lazada API connection, order sync, and troubleshooting steps.*`,
  },
  {
    id: 'kb-012',
    title: 'Flash sale rules and fair use policy',
    category: 'Promotions & Discounts',
    status: 'published',
    languages: ['en', 'id', 'th'],
    aiUsageCount: 298,
    deflectionScore: 71,
    lastUpdated: '29 Apr 2026',
    author: 'Priya Nair',
    views: 765,
    content: `## Flash Sale Policy\n\nDuring flash sales, the following rules apply:\n\n- One order per customer per flash sale item\n- No order modifications after placement\n- Flash sale prices cannot be combined with voucher codes\n- Orders not paid within 15 minutes are automatically cancelled\n\nFlash sales run for a limited time. Stock is not guaranteed.`,
  },
];